backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'
    
media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    delete: false
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Slides", name: "slides", widget: "list", fields: [{label: "Slide Blurb", name: "slideBlurb", widget: "text"}, {label: "Slide Image", name: "slideImg", widget: image}, {label: "Sidebar Hero", name: "sidebarHero", widget: "text"}, {label: "Sidebar Description", name: "sidebarDescription", widget: "text"}]}
          - {label: "Gallery", name: "galleryImages", widget: "list", field: {label: Image, name: image, widget: image}}

      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Header Image", name: "headerImage", widget: image}
          - {label: "Hero Image", name: "heroImage", widget: image}
          - {label: "Section 1", name: "section1", widget: "object", fields: [
              {label: "title", name: "title", widget: "text"}, 
              {label: "Description", name: "description", widget: "text"},
              {label: "Image", name: "image", widget: image}
            ]}
          - {label: "Section 2", name: "section2", widget: "object", fields: [
              {label: "title", name: "title", widget: "string"},
              {label: "Description", name: "description", widget: "text"}, 
              {label: "Image 1", name: "image1", widget: image},
              {label: "Image 2", name: "image2", widget: image},
              {label: "Image 3", name: "image3", widget: image},
              {label: "Image 4", name: "image4", widget: image},
            ]}
          - {label: "Section 3", name: "section3", widget: "object", fields: [
              {label: "title", name: "title", widget: "string"},
            ]}
          - {label: "Section 4", name: "section4", widget: "object", fields: [
              {label: "title", name: "title", widget: "string"},
              {label: "Description", name: "description", widget: "list", fields: [
                {name: "text", widget: "string"},
              ]},
            ]}
          - {label: "Section 5", name: "section5", widget: "object", fields: [
              {label: "title", name: "title", widget: "string"},
              {label: "Description", name: "description", widget: "list", fields: [
                {name: "text", widget: "string"},
              ]}
            ]}
            
      - file: "src/pages/resources/index.md"
        label: "Resources"
        name: "resources"
        fields:
          - {label: "Top Left Asset Download Card Image", name: "topLeftDownloadImage", widget: "image"}
          - {label: "Top Left Asset Download Card", name: "topLeftDownloadText", widget: "string"}
          - {label: "Top Left Asset Download Card File", name: "topLeftDownloadImageFile", widget: "file"}
          - {label: "Top Right Asset Download Card Image", name: "topRightDownloadImage", widget: "image"}
          - {label: "Top Right Asset Download Card", name: "topRightDownloadCard", widget: "string"}
          - {label: "Top Right Asset Download Card File", name: "topRightDownloadFile", widget: "file"}
          - {label: "Page Body Text", name: "bodyText", widget: "markdown"}
          - {label: "Bottom Row 1 Left Asset Download Card", name: "btmRow1LeftDownloadImage", widget: "image"}
          - {label: "Bottom Row 1 Left Asset Download Card", name: "btmRow1LeftDownloadText", widget: "string"}
          - {label: "Bottom Row 1 Left Asset Download Card", name: "btmRow1LeftDownloadFile", widget: "file"}
          - {label: "Bottom Row 1 Right Asset Download Card", name: "btmRow1RightDownloadImage", widget: "image"}
          - {label: "Bottom Row 1 Right Asset Download Card", name: "btmRow1RightDownloadText", widget: "string"}
          - {label: "Bottom Row 1 Right Asset Download Card", name: "btmRow1RightDownloadFile", widget: "file"}
          - {label: "Bottom Row 2 Left Asset Download Card", name: "btmRow2LeftDownloadImage", widget: "image"}
          - {label: "Bottom Row 2 Left Asset Download Card", name: "btmRow2LeftDownloadText", widget: "string"}
          - {label: "Bottom Row 2 Left Asset Download Card", name: "btmRow2LeftDownloadFile", widget: "file"}
          - {label: "Bottom Row 2 Right Asset Download Card", name: "btmRow2RightDownloadImage", widget: "image"}
          - {label: "Bottom Row 2 Right Asset Download Card", name: "btmRow2RightDownloadText", widget: "string"}
          - {label: "Bottom Row 2 Right Asset Download Card", name: "btmRow2RightDownloadFile", widget: "file"}
          - {label: "Bottom Row 3 Left Asset Download Card", name: "btmRow3LeftDownloadImage", widget: "image"}
          - {label: "Bottom Row 3 Left Asset Download Card", name: "btmRow3LeftDownloadText", widget: "string"}
          - {label: "Bottom Row 3 Left Asset Download Card", name: "btmRow3LeftDownloadFile", widget: "file"}
          - {label: "Bottom Row 3 Right Asset Download Card", name: "btmRow3RightDownloadImage", widget: "image"}
          - {label: "Bottom Row 3 Right Asset Download Card", name: "btmRow3RightDownloadText", widget: "string"}
          - {label: "Bottom Row 3 Right Asset Download Card", name: "btmRow3RightDownloadFile", widget: "file"}

      - file: "src/pages/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: "Title", name: "title", widget: "markdown"}
          - {label: "Contact Number", name: "contactnumber", widget: "string"}
          - {label: "Contact Email One", name: "contactnumberone", widget: "string"}
          - {label: "Contact Email Two", name: "contactnumbertwo", widget: "string"}
          - {label: "Sidebar Content", name: "sidebarcontent", widget: "list", fields: [
                {label: "title", name: "title", widget: "string"}, 
                {label: "Description", name: "description", widget: "text"},
            ]}

  - name: "team"
    label: "Team"
    folder: "src/pages/team"
    create: true
    delete: true
    slug: "team/{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "Teamdetail/index"}
      - {label: "Date Posted", name: "date", widget: "datetime"}
      - {label: "Member Image", name: "memberimage", widget: image}
      - {label: "Member Resume", name: "resume", widget: "file"}
      - {label: "Member Name", name: "title", widget: "string"}
      - {label: "Designation", name: "designation", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}

  - name: "category"
    label: "Work Categories"
    folder: "src/pages/categories"
    create: true
    delete: true
    slug: "category/{{slug}}"
    identifier_field: categoryname
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "projectcat"}
      - {label: "Category Name", name: "categoryname", widget: "string"}

  - name: "project"
    label: "Work"
    folder: "src/pages/project"
    create: true
    delete: true
    slug: "project/{{slug}}"
    identifier_field: projectname
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "Projectdetail/index"}
      - {label: "Work Name", name: "projectname", widget: "string"}
      - {label: "Work Tagline", name: "projecttagline", widget: "string"}
      - {label: "Work Image", name: "projectimage", widget: image}
      - {label: "Work Category", valueField: "categoryname", searchFields: "categoryname", displayFields: "categoryname", collection: "category", name: "projectcategory", widget: "relation"}
      - {label: "Work Scope", name: "projectscope", widget: "string"}
      - {label: "Date Posted", name: "date", widget: "datetime"}
      - {label: "Sort Description", name: "sortdescription", widget: "string"}
      - {label: "Description Blocks", name: "descriptionblockone", widget: "list", fields: [
          {name: "descriptiontitle", label: "Block Title", widget: "string"},
          {name: "imagepos", label: "Block Image Position", widget: "select", options: ["left","right"]},
          {name: "image", label: Block Image, widget: image}, 
          {name: "description", label: Block Description, widget: "markdown"}
        ]}
      - {label: "More Fields", name: "extrafield", widget: "list", fields: [
          {name: "label", label: Label,  widget: "string"}, {name: "value", label: Value, widget: "string"}
        ]}
      
  - name: "footer"
    label: "Footer"
    folder: "src/pages/footer"
    identifier_field: copyrightcontent
    delete: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "footer-page"}
      - {label: "Copyright Content", name: "copyrightcontent", widget: "string"}
      - {label: "Logo Image", name: "image", widget: "image"}
      - {label: "Contact Number", name: "contactnumber", widget: "string"}
      - {label: "Contact Email One", name: "contactnumberone", widget: "string"}
      - {label: "Address 1", name: "address1", widget: "string"}
      - {label: "Address 2", name: "address2", widget: "string"}


  

 
  

     

      
